In [1]:
import add_path
import torch
import torch.nn as nn
import torch.nn.functional as F
import pickle

In [2]:
from transformers import AutoTokenizer
from models.BERT.tucoregcn_bert_pytorch import TUCOREGCN_BertForSequenceClassification, TUCOREGCN_BertConfig
tokenizer = AutoTokenizer.from_pretrained("bert-base-uncased")
tucore_gcn_bert = TUCOREGCN_BertForSequenceClassification(TUCOREGCN_BertConfig.from_json_file("../models/BERT/tucoregcn_bert_mlc.json"))
tucore_gcn_bert.cuda()

d:\projects\affect\TUCORE-GCN\.venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


d:\projects\affect\TUCORE-GCN\.venv\Lib\site-packages\dgl\dgl.dll
False
False


TUCOREGCN_BertForSequenceClassification(
  (tucoregcn_bert): TUCOREGCN_Bert(
    (bert): BertModel(
      (embeddings): BertEmbeddings(
        (word_embeddings): Embedding(30522, 768, padding_idx=0)
        (position_embeddings): Embedding(512, 768)
        (token_type_embeddings): Embedding(2, 768)
        (speaker_embeddings): Embedding(512, 768)
        (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
        (dropout): Dropout(p=0.1, inplace=False)
      )
      (encoder): BertEncoder(
        (layer): ModuleList(
          (0-11): 12 x BertLayer(
            (attention): BertAttention(
              (self): BertSelfAttention(
                (query): Linear(in_features=768, out_features=768, bias=True)
                (key): Linear(in_features=768, out_features=768, bias=True)
                (value): Linear(in_features=768, out_features=768, bias=True)
                (dropout): Dropout(p=0.1, inplace=False)
              )
              (output): BertSelfOutpu

In [3]:
tucore_gcn_bert.load_state_dict(torch.load("../TUCOREGCN_BERT_DialogRE/tucoregcn_pytorch_model.pt", map_location="cuda"))
tucore_gcn_bert.cuda()

TUCOREGCN_BertForSequenceClassification(
  (tucoregcn_bert): TUCOREGCN_Bert(
    (bert): BertModel(
      (embeddings): BertEmbeddings(
        (word_embeddings): Embedding(30522, 768, padding_idx=0)
        (position_embeddings): Embedding(512, 768)
        (token_type_embeddings): Embedding(2, 768)
        (speaker_embeddings): Embedding(512, 768)
        (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
        (dropout): Dropout(p=0.1, inplace=False)
      )
      (encoder): BertEncoder(
        (layer): ModuleList(
          (0-11): 12 x BertLayer(
            (attention): BertAttention(
              (self): BertSelfAttention(
                (query): Linear(in_features=768, out_features=768, bias=True)
                (key): Linear(in_features=768, out_features=768, bias=True)
                (value): Linear(in_features=768, out_features=768, bias=True)
                (dropout): Dropout(p=0.1, inplace=False)
              )
              (output): BertSelfOutpu

In [4]:
from data import TUCOREGCNDataset, TUCOREGCNDataloader
dev_set = TUCOREGCNDataset(src_file="../datasets/DialogRE", save_file="../datasets/DialogRE/dev_BERT.pkl", max_seq_length=512, tokenizer=tokenizer, n_class=36, encoder_type='BERT')
dev_loader = TUCOREGCNDataloader(dataset=dev_set, batch_size=2, shuffle=False, relation_num=36, max_length=512)


Reading data from ../datasets/DialogRE.
load preprocessed data from ../datasets/DialogRE/dev_BERT.pkl.


In [5]:
idx, batch = next(enumerate(dev_loader))
entry_idx = 0
input_ids = batch["input_ids"].to("cuda:0")
segment_ids = batch["segment_ids"].to("cuda:0")
input_mask = batch["input_masks"].to("cuda:0")
speaker_ids = batch["speaker_ids"].to("cuda:0")
graphs = batch["graphs"]
mention_id = batch["mention_ids"].to("cuda:0")
turn_mask = batch["turn_masks"].to("cuda:0")

In [6]:
output = tucore_gcn_bert(
	input_ids,
	segment_ids,
	input_mask,
	speaker_ids,
	graphs,
	mention_id,
	None,
	turn_mask
)
output

{'input_ids': torch.Size([2, 512]), 'token_type_ids': torch.Size([2, 512]), 'attention_mask': torch.Size([2, 512]), 'speaker_ids': torch.Size([2, 512]), 'graphs': [Graph(num_nodes={'node': 23},
      num_edges={('node', 'dialog', 'node'): 40, ('node', 'entity', 'node'): 24, ('node', 'speaker', 'node'): 114},
      metagraph=[('node', 'node', 'dialog'), ('node', 'node', 'entity'), ('node', 'node', 'speaker')]), Graph(num_nodes={'node': 23},
      num_edges={('node', 'dialog', 'node'): 40, ('node', 'entity', 'node'): 10, ('node', 'speaker', 'node'): 114},
      metagraph=[('node', 'node', 'dialog'), ('node', 'node', 'entity'), ('node', 'node', 'speaker')])], 'mention_ids': torch.Size([2, 512]), 'turn_mask': torch.Size([2, 512, 512])}
{'input_ids': tensor([[ 101,    3, 1024,  ...,  102,    3,  102],
        [ 101, 5882, 1015,  ...,  102, 4005,  102]], device='cuda:0'), 'token_type_ids': tensor([[1, 1, 1,  ..., 1, 1, 1],
        [1, 1, 1,  ..., 1, 1, 1]], device='cuda:0'), 'attention_mask'

SequenceClassifierOutput(loss=None, logits=tensor([[ -4.8410,  -3.6483,  -3.9309,  -2.8273,  -3.2758,  -3.6839,  -0.7073,
          -4.5233,  -2.9430,  -6.5784,  -2.1321,  -5.3965,  -2.6291,  -2.7485,
          -3.1896,  -3.5896,  -2.8359,  -7.4138, -10.3252,  -7.4138,  -9.1247,
          -7.0680,  -6.9347,  -6.0047,  -7.4065,  -7.6085,  -8.2772,  -6.4487,
          -7.6898,  -4.4147,  -5.4266,  -7.9759, -11.8575,  -6.3400,  -5.2046,
          -5.1611],
        [ -8.7905,  -7.0357, -11.0352,  -5.5062,  -7.9179,  -6.2430,  -5.4437,
         -11.2843,  -7.1623, -12.9512,  -7.1544, -10.8570,  -9.5506,  -5.7982,
          -9.5459,  -8.6775,  -7.7129,  -7.4305, -14.6312,  -8.3071,  -8.4468,
          -9.2358,  -9.7711,  -7.3290, -10.2544, -15.4221, -11.8138, -10.5894,
           5.5214,  -4.1414,  -5.3511,  -7.3361, -11.7879,  -9.8088,  -9.9927,
          -8.2075]], device='cuda:0', grad_fn=<AddmmBackward0>), hidden_states=None, attentions=tensor([[[[1.1111, 0.0000, 0.0000,  ..., 0.0000, 0.

In [7]:
output.logits.argmax(1)

tensor([ 6, 28], device='cuda:0')

In [1]:
import add_path
import torch
import torch.nn as nn
import torch.nn.functional as F
import pickle
from transformers import pipeline
from transformers.pipelines import PIPELINE_REGISTRY
from models.BERT.speaker_tokens import SpeakerBertTokenizer
from models.BERT.tucorecgcn_bert_pytorch_pipeline import ConversationalSequenceClassificationPipeline
from models.BERT.tucoregcn_bert_pytorch import TUCOREGCN_BertForSequenceClassification, TUCOREGCN_BertConfig
import os
os.environ['CUDA_LAUNCH_BLOCKING'] = "1"
PIPELINE_REGISTRY.register_pipeline(
    "conversational-sequence-classification",
    pipeline_class=ConversationalSequenceClassificationPipeline
)
speaker_tokenizer = SpeakerBertTokenizer.from_pretrained('bert-base-uncased')
model = TUCOREGCN_BertForSequenceClassification(TUCOREGCN_BertConfig.from_json_file("../models/BERT/tucoregcn_bert_mlc.json"))
model.cuda()
model.load_state_dict(torch.load("../TUCOREGCN_BERT_DialogRE/tucoregcn_pytorch_model.pt"))
model.cuda()
classifier = pipeline("conversational-sequence-classification", model=model, tokenizer=speaker_tokenizer, device="cuda:0")



d:\projects\affect\TUCORE-GCN\.venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


d:\projects\affect\TUCORE-GCN\.venv\Lib\site-packages\dgl\dgl.dll


The tokenizer class you load from this checkpoint is not the same type as the class this function is called from. It may result in unexpected tokenization. 
The tokenizer class you load from this checkpoint is 'BertTokenizer'. 
The class this function is called from is 'SpeakerBertTokenizer'.


False
False


In [2]:
from models.BERT.tucoregcn_bert_pytorch_processor import SpeakerRelation, Conversation, Message

c = Conversation(
	messages=[
		Message("Speaker 1", "Howdy! I'm Flowey, Flowey the Flower!"),
		Message("Speaker 2", "Hello Flowey."),
	],
	speaker_relations=[
		SpeakerRelation("Speaker 1", "Speaker 2", [3])
	]
)
classifier(c)

{'input_ids': torch.Size([1, 512]), 'token_type_ids': torch.Size([1, 512]), 'attention_mask': torch.Size([1, 512]), 'speaker_ids': torch.Size([1, 512]), 'graphs': [Graph(num_nodes={'node': 5},
      num_edges={('node', 'dialog', 'node'): 4, ('node', 'entity', 'node'): 8, ('node', 'speaker', 'node'): 1},
      metagraph=[('node', 'node', 'dialog'), ('node', 'node', 'entity'), ('node', 'node', 'speaker')])], 'mention_ids': torch.Size([1, 512]), 'turn_mask': torch.Size([1, 512, 512])}
{'input_ids': tensor([[ 101,   11, 2129, 5149,  999, 1045, 1005, 1049, 4834, 3240, 1010, 4834,
         3240, 1996, 6546,  999,   12, 7592, 4834, 3240, 1012,  102,   11,  102,
           12,  102,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0

We strongly recommend passing in an `attention_mask` since your input_ids may be padded. See https://huggingface.co/docs/transformers/troubleshooting#incorrect-output-when-padding-tokens-arent-masked.


tensor([[ 101,   11, 2129, 5149,  999, 1045, 1005, 1049, 4834, 3240, 1010, 4834,
         3240, 1996, 6546,  999,   12, 7592, 4834, 3240, 1012,  102,   11,  102,
           12,  102,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,  

d:\projects\affect\TUCORE-GCN\models\BERT\tucorecgcn_bert_pytorch_pipeline.py:323: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  probabilities = F.softmax(logits)


{'label': ['LABEL_14'],
 'score': [0.33398374915122986],
 'logits': [[-6.00899600982666,
   -4.544610500335693,
   -6.698363304138184,
   -4.116959095001221,
   -5.802485466003418,
   -5.37537145614624,
   -5.542641639709473,
   -8.46031665802002,
   -5.55460786819458,
   -7.048425197601318,
   -4.928355693817139,
   -6.537173271179199,
   -2.317607879638672,
   -3.280219793319702,
   -1.6410108804702759,
   -6.400602340698242,
   -1.9220244884490967,
   -9.677318572998047,
   -13.731180191040039,
   -11.12903881072998,
   -12.00004768371582,
   -7.024866580963135,
   -9.708110809326172,
   -5.761183261871338,
   -7.499666690826416,
   -9.901050567626953,
   -12.585268020629883,
   -5.523062229156494,
   -5.182820796966553,
   -3.547401189804077,
   -7.338206768035889,
   -7.698788642883301,
   -10.658377647399902,
   -6.6471848487854,
   -7.222543239593506,
   -8.640364646911621]]}

[0]

In [ ]:
import numpy as np
np.array([np.array([1,2,3])])

array([[1, 2, 3]])

In [8]:
print("\n".join(list(tucore_gcn_bert.state_dict().keys())))

tucoregcn_bert.bert.embeddings.word_embeddings.weight
tucoregcn_bert.bert.embeddings.position_embeddings.weight
tucoregcn_bert.bert.embeddings.token_type_embeddings.weight
tucoregcn_bert.bert.embeddings.speaker_embeddings.weight
tucoregcn_bert.bert.embeddings.LayerNorm.weight
tucoregcn_bert.bert.embeddings.LayerNorm.bias
tucoregcn_bert.bert.encoder.layer.0.attention.self.query.weight
tucoregcn_bert.bert.encoder.layer.0.attention.self.query.bias
tucoregcn_bert.bert.encoder.layer.0.attention.self.key.weight
tucoregcn_bert.bert.encoder.layer.0.attention.self.key.bias
tucoregcn_bert.bert.encoder.layer.0.attention.self.value.weight
tucoregcn_bert.bert.encoder.layer.0.attention.self.value.bias
tucoregcn_bert.bert.encoder.layer.0.attention.output.dense.weight
tucoregcn_bert.bert.encoder.layer.0.attention.output.dense.bias
tucoregcn_bert.bert.encoder.layer.0.attention.output.LayerNorm.weight
tucoregcn_bert.bert.encoder.layer.0.attention.output.LayerNorm.bias
tucoregcn_bert.bert.encoder.layer.0

In [ ]:
import dgl
sequence_outputs = output["sequence_outputs"]
pooled_outputs = output["pooled_outputs"]
mention_ids = batch["mention_ids"].to("cuda:0")
graphs = batch["graphs"]
#initialize some variables
features = None
num_batch_turn = []
slen = input_ids.size(1)
# Iterate over all inputs to be processed
for i in range(len(graphs)):
	sequence_output = sequence_outputs[i]
	mention_id = mention_ids[i]
	pooled_output = pooled_outputs[i]
	# Find the last turn (in the case of tucoregcn, it is the masked speaker dictionary)
	mention_num = torch.max(mention_id)
	# Create a mention matrix idx of mention_num*slen
	num_batch_turn.append(mention_num + 1)
	mention_index = (
		(torch.arange(mention_num) + 1).unsqueeze(1).expand(-1, slen)
	)
	if torch.cuda.is_available():
		mention_index = mention_index.cuda()
	# Create a mentions matrix of slen*mention_num
	mentions = mention_id.unsqueeze(0).expand(mention_num, -1)
	# Generate truth matrix of each speaker's dialogue over the entire conversation
	select_metrix = (mention_index == mentions).float()
	# Factor into the one-hot encoding, the total number of words in each speaker's dialogue
	word_total_numbers = (
		torch.sum(select_metrix, dim=-1).unsqueeze(-1).expand(-1, slen)
	)
	select_metrix = torch.where(
		word_total_numbers > 0,
		select_metrix / word_total_numbers,
		select_metrix,
	)
	# Apply one hot encoding to sequence_output to selectively obtain features
	x = torch.mm(select_metrix, sequence_output)
	x = torch.cat((pooled_output.unsqueeze(0), x), dim=0)
	# Iteratively concatenate features from all sequence_outputs
	if features is None:
		features = x
	else:
		features = torch.cat((features, x), dim=0)
# Batch dgl graphs into 1 graph for efficient computation
graph_big = dgl.batch(graphs)
output_features = [features]

In [115]:
num_batch_turn

[tensor(23, device='cuda:0'), tensor(23, device='cuda:0')]

In [106]:
lstm = tucore_gcn_bert.tucoregcn_bert.LSTM_layers[0]

In [111]:
new_features = []
new_features.append(features[0])
lstm_out = lstm(features[0 + 1 : 0 + idx - 2].unsqueeze(0))
lstm_out

tensor([[-0.0296, -0.1093, -0.0949,  ...,  0.0403, -0.0775,  0.0609],
        [ 0.0269, -0.1400, -0.0430,  ...,  0.0400, -0.0286,  0.0603],
        [ 0.0338, -0.0955, -0.0860,  ...,  0.0678, -0.0762,  0.0849],
        ...,
        [ 0.0447, -0.0806, -0.0882,  ...,  0.0112, -0.0611,  0.0586],
        [-0.0022, -0.0971, -0.0838,  ...,  0.0282, -0.0546,  0.0250],
        [ 0.0282, -0.0570, -0.0888,  ...,  0.0342, -0.0482,  0.0617]],
       device='cuda:0', grad_fn=<AddmmBackward0>)

In [103]:
output_features

[tensor([[ 4.5792e-01, -1.1729e-02,  3.2297e-01,  ..., -3.7483e-01,
           4.0892e-01, -7.1791e-01],
         [-4.3282e-01, -1.8977e-01,  7.0841e-01,  ...,  7.7599e-01,
          -5.2889e-01, -1.2678e+00],
         [-1.0421e+00, -5.9411e-01,  1.3200e+00,  ...,  2.7433e-01,
          -4.1637e-01, -1.2198e+00],
         ...,
         [ 2.4836e-01, -7.2986e-01,  1.8437e-01,  ...,  6.4670e-01,
          -1.1878e+00, -2.2512e-01],
         [ 1.4898e-01, -6.1494e-01, -5.7474e-01,  ...,  1.6153e+00,
          -2.0723e+00, -3.3880e-01],
         [ 1.2348e+00, -4.7497e-01, -5.3483e-01,  ..., -1.4764e-03,
          -1.1713e+00, -2.1761e-01]], device='cuda:0', grad_fn=<CatBackward0>)]

In [97]:
[4,7,8]+=[2]

SyntaxError: 'list' is an illegal expression for augmented assignment (2151216791.py, line 1)

In [5]:
import dgl
sequence_output = output["sequence_outputs"][0]
pooled_output = output["pooled_outputs"][0]
mention_id = batch["mention_ids"].to("cuda:0")[0]

#initialize some variables
slen = input_ids.size(1)
# Find the last turn (in the case of tucoregcn, it is the masked speaker dictionary)
mention_num = torch.max(mention_id)
# Create a mention matrix idx of mention_num*slen
num_batch_turn = mention_num + 1
mention_index = (
	(torch.arange(mention_num) + 1).unsqueeze(1).expand(-1, slen)
)
if torch.cuda.is_available():
	mention_index = mention_index.cuda()
# Create a mentions matrix of slen*mention_num
mentions = mention_id.unsqueeze(0).expand(mention_num, -1)
# Generate 1 hot encoding of each speaker's dialogue
select_metrix = (mention_index == mentions).float()
# Factor into the one-hot encoding, the total number of words in each speaker's dialogue
word_total_numbers = (
	torch.sum(select_metrix, dim=-1).unsqueeze(-1).expand(-1, slen)
)
select_metrix = torch.where(
	word_total_numbers > 0,
	select_metrix / word_total_numbers,
	select_metrix,
)
# Apply one hot encoding to sequence_output to selectively obtain features
features = torch.mm(select_metrix, sequence_output)
features = torch.cat((pooled_output.unsqueeze(0), features), dim=0)

In [94]:
val, ind = torch.max(torch.LongTensor([[1,2,3],[1,2,4]]),dim=1)
ind

tensor([2, 2])

In [29]:
torch.ones(3,5)

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [30]:
mention_nums

tensor([22, 22], device='cuda:0')

tensor([[6, 6, 6, 6, 6, 6, 6, 6],
        [7, 7, 7, 7, 7, 7, 7, 7],
        [8, 8, 8, 8, 8, 8, 8, 8]])

In [95]:
select_metrix

tensor([[0.0000, 0.2500, 0.2500,  ..., 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
        ...,
        [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000,  ..., 0.0000, 1.0000, 0.0000]],
       device='cuda:0')

In [88]:
(torch.arange(5) + 1).unsqueeze(1)

tensor([[1],
        [2],
        [3],
        [4],
        [5]])

In [87]:
temp = torch.LongTensor([6,7,8])
result = torch.arange(0, torch.max(temp)+1).expand(len(temp), -1)
result#>temp.expand(torch.max(temp)+1,-1).T

tensor([[0, 1, 2, 3, 4, 5, 6, 7, 8],
        [0, 1, 2, 3, 4, 5, 6, 7, 8],
        [0, 1, 2, 3, 4, 5, 6, 7, 8]])

In [94]:
result.unsqueeze(2)

tensor([[[0],
         [1],
         [2],
         [3],
         [4],
         [5],
         [6],
         [7],
         [8]],

        [[0],
         [1],
         [2],
         [3],
         [4],
         [5],
         [6],
         [7],
         [8]],

        [[0],
         [1],
         [2],
         [3],
         [4],
         [5],
         [6],
         [7],
         [8]]])

In [90]:
result>torch.LongTensor([6,7,8]).unsqueeze(-1)

tensor([[False, False, False, False, False, False, False,  True,  True],
        [False, False, False, False, False, False, False, False,  True],
        [False, False, False, False, False, False, False, False, False]])

In [78]:
mention_index

tensor([[ 1,  1,  1,  ...,  1,  1,  1],
        [ 2,  2,  2,  ...,  2,  2,  2],
        [ 3,  3,  3,  ...,  3,  3,  3],
        ...,
        [20, 20, 20,  ..., 20, 20, 20],
        [21, 21, 21,  ..., 21, 21, 21],
        [22, 22, 22,  ..., 22, 22, 22]], device='cuda:0')

In [76]:
batch["mention_ids"].to("cuda:0")

tensor([[ 0,  1,  1,  ...,  0, 22,  0],
        [ 0,  1,  1,  ...,  0, 22,  0]], device='cuda:0')

In [16]:
sequence_outputs = output["sequence_outputs"]
pooled_outputs = output["pooled_outputs"]
graphs = batch["graphs"]
mention_ids = batch["mention_ids"].to("cuda:0")
mention_ids
#initialize some variables
slen = input_ids.size(1)
# Find the last turn (in the case of tucoregcn, it is the masked speaker dictionary)
mention_nums, _ = torch.max(mention_ids,dim=1)
num_batch_turns = mention_nums + 1
'''
mention_index = (
	(torch.arange(mention_nums,dim=1) + 1).unsqueeze(1).expand(-1, slen)
)
if torch.cuda.is_available():
	mention_index = mention_index.cuda()'''
mentions = mention_ids.unsqueeze(1).expand(-1, mention_num, -1)
mentions

TypeError: arange() received an invalid combination of arguments - got (Tensor, dim=int), but expected one of:
 * (Number end, *, Tensor out, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)
 * (Number start, Number end, *, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)
 * (Number start, Number end, Number step, *, Tensor out, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)


In [73]:
mention_ids.shape

torch.Size([2, 512])

In [65]:
mention_id.unsqueeze(0).expand(mention_num, -1)

tensor([[ 0,  1,  1,  ...,  0, 22,  0],
        [ 0,  1,  1,  ...,  0, 22,  0],
        [ 0,  1,  1,  ...,  0, 22,  0],
        ...,
        [ 0,  1,  1,  ...,  0, 22,  0],
        [ 0,  1,  1,  ...,  0, 22,  0],
        [ 0,  1,  1,  ...,  0, 22,  0]], device='cuda:0')

In [71]:
mention_ids.unsqueeze(1).expand(-1, mention_num, -1)[0]

tensor([[ 0,  1,  1,  ...,  0, 22,  0],
        [ 0,  1,  1,  ...,  0, 22,  0],
        [ 0,  1,  1,  ...,  0, 22,  0],
        ...,
        [ 0,  1,  1,  ...,  0, 22,  0],
        [ 0,  1,  1,  ...,  0, 22,  0],
        [ 0,  1,  1,  ...,  0, 22,  0]], device='cuda:0')

In [64]:
input_ids.size(1)

512

In [78]:
torch.sum((mention_index==mentions).float(), dim=-1).unsqueeze(-1).expand(-1, slen)

tensor([[ 4.,  4.,  4.,  ...,  4.,  4.,  4.],
        [ 5.,  5.,  5.,  ...,  5.,  5.,  5.],
        [12., 12., 12.,  ..., 12., 12., 12.],
        ...,
        [75., 75., 75.,  ..., 75., 75., 75.],
        [ 2.,  2.,  2.,  ...,  2.,  2.,  2.],
        [ 1.,  1.,  1.,  ...,  1.,  1.,  1.]], device='cuda:0')

In [80]:
select_metrix[1]

tensor([0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.2000, 0.2000, 0.2000, 0.2000,
        0.2000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 

In [76]:
(mention_index==mentions).float()[1]

tensor([0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 

In [70]:
select_metrix

tensor([[0.0000, 0.2500, 0.2500,  ..., 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
        ...,
        [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000,  ..., 0.0000, 1.0000, 0.0000]],
       device='cuda:0')

In [68]:
mentions.shape

torch.Size([22, 512])

In [69]:
(torch.arange(mention_num) + 1).unsqueeze(1).expand(-1, slen).shape

torch.Size([22, 512])

In [6]:
tokenizer.convert_ids_to_tokens(input_ids[1])

['[CLS]',
 'speaker',
 '1',
 ':',
 'hey',
 '!',
 'speaker',
 '2',
 ':',
 'hey',
 '.',
 'speaker',
 '3',
 ':',
 'hey',
 ',',
 'man',
 '.',
 'what',
 "'",
 's',
 'up',
 '?',
 'speaker',
 '1',
 ':',
 'maybe',
 'you',
 'can',
 'tell',
 'me',
 '.',
 'my',
 'agent',
 'would',
 'like',
 'to',
 'know',
 'why',
 'i',
 'didn',
 "'",
 't',
 'show',
 'up',
 'at',
 'the',
 'audition',
 'i',
 'didn',
 "'",
 't',
 'know',
 'i',
 'had',
 'today',
 '.',
 'the',
 'first',
 'good',
 'thing',
 'she',
 'gets',
 'me',
 'in',
 'weeks',
 '.',
 'how',
 'could',
 'you',
 'not',
 'give',
 'me',
 'the',
 'message',
 '?',
 '!',
 'speaker',
 '3',
 ':',
 'well',
 ',',
 'i',
 "'",
 'll',
 'tell',
 'ya',
 'i',
 'do',
 'enjoy',
 'guilt',
 ',',
 'but',
 ',',
 'ah',
 ',',
 'it',
 'wasn',
 "'",
 't',
 'me',
 '.',
 'speaker',
 '2',
 ':',
 'yes',
 ',',
 'it',
 'was',
 '!',
 'it',
 'was',
 'him',
 '!',
 'uh',
 'huh',
 '!',
 'okay',
 ',',
 'it',
 'was',
 'me',
 '!',
 'speaker',
 '1',
 ':',
 'how',
 'is',
 'it',
 'you',
 '?',


In [5]:
tokenizer.convert_tokens_to_string(tokenizer.convert_ids_to_tokens(input_ids[1]))

"[CLS] speaker 1 : hey! speaker 2 : hey. speaker 3 : hey, man. what ' s up? speaker 1 : maybe you can tell me. my agent would like to know why i didn ' t show up at the audition i didn ' t know i had today. the first good thing she gets me in weeks. how could you not give me the message?! speaker 3 : well, i ' ll tell ya i do enjoy guilt, but, ah, it wasn ' t me. speaker 2 : yes, it was! it was him! uh huh! okay, it was me! speaker 1 : how is it you? speaker 2 : well, it was just, it was all so crazy, you know. i mean, chandler was in the closet, counting to 10, and he was up to 7 and i hadn ' t found a place to hide yet. i - i - i meant to tell you, and i wrote it all down on my hand. see, all of it. speaker 1 : yep, that ' s my audition. speaker 4 : see, now this is why i keep notepads everywhere. speaker 2 : yep, and that ' s why we don ' t invite you to play. speaker 5 : what is the great tragedy here? you go get yourself another appointment. speaker 1 : well, estelle tried, you kn

In [57]:
turn_mask[0]

tensor([[1, 0, 0,  ..., 0, 0, 0],
        [0, 1, 1,  ..., 0, 0, 0],
        [0, 1, 1,  ..., 0, 0, 0],
        ...,
        [0, 0, 0,  ..., 1, 0, 0],
        [0, 0, 0,  ..., 0, 1, 0],
        [0, 0, 0,  ..., 0, 0, 1]], device='cuda:0')

In [52]:
mention_id

tensor([ 0,  1,  1,  1,  1,  2,  2,  2,  2,  2,  3,  3,  3,  3,  3,  3,  3,  3,
         3,  3,  3,  3,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,
         4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,
         4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,
         4,  4,  4,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,
         5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  6,  6,  6,  6,  6,  6,  6,  6,
         6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  7,  7,  7,  7,  7,
         7,  7,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,
         8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,
         8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,
         8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,
         8,  8,  8,  8,  8,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9, 10, 10, 10,
        10, 10, 10, 10, 10, 10, 10, 10, 

In [43]:
mentions.shape

torch.Size([22, 512])

In [38]:
mention_id.shape

torch.Size([512])

In [39]:
mention_index.shape

torch.Size([22, 512])

In [13]:
state_dict = torch.load("../TUCOREGCN_BERT_DialogRE/tucoregcn_pytorch_model.pt", map_location="cuda")
for key in list(state_dict.keys()):
    state_dict[key.replace("tucoregcn_bert.turnAttention.fc.weight", "tucoregcn_bert.turnAttention.out_lin.weight")] = state_dict.pop(key)

In [14]:
print("\n".join(list(state_dict.keys())))

tucoregcn_bert.bert.embeddings.word_embeddings.weight
tucoregcn_bert.bert.embeddings.position_embeddings.weight
tucoregcn_bert.bert.embeddings.token_type_embeddings.weight
tucoregcn_bert.bert.embeddings.speaker_embeddings.weight
tucoregcn_bert.bert.embeddings.LayerNorm.weight
tucoregcn_bert.bert.embeddings.LayerNorm.bias
tucoregcn_bert.bert.encoder.layer.0.attention.self.query.weight
tucoregcn_bert.bert.encoder.layer.0.attention.self.query.bias
tucoregcn_bert.bert.encoder.layer.0.attention.self.key.weight
tucoregcn_bert.bert.encoder.layer.0.attention.self.key.bias
tucoregcn_bert.bert.encoder.layer.0.attention.self.value.weight
tucoregcn_bert.bert.encoder.layer.0.attention.self.value.bias
tucoregcn_bert.bert.encoder.layer.0.attention.output.dense.weight
tucoregcn_bert.bert.encoder.layer.0.attention.output.dense.bias
tucoregcn_bert.bert.encoder.layer.0.attention.output.LayerNorm.weight
tucoregcn_bert.bert.encoder.layer.0.attention.output.LayerNorm.bias
tucoregcn_bert.bert.encoder.layer.0

In [15]:
torch.save(state_dict, "../TUCOREGCN_BERT_DialogRE/tucoregcn_pytorch_model.pt")